### ISSUE TITLE
The item doesn't seem to drop from the block

### ISSUE THREAD

**Issue by Shichiha** [Slexom/animal-feeding-trough#32] opened 2024-07-27 19:41 UTC
Like, when you break it with an iron axe it doesn't drop. Is this a bug or feature?

Minecraft Version: 1.21
Mod Version: 1.1.1+1.21 from Modrinth

**Comment by pommellie** [comment] 2024-08-08 04:40
I am also having this issue on the same Minecraft version (1.21).

**Comment by Slexom** [comment] 2024-09-22 08:55
the issue is fixed in version 1.1.2. Is already live on Curseforge, I'm going to add it to modrint too(I always forget to update Modrinth too >.<)

**Closed as completed by Slexom** 2024-09-22 08:55 UTC
